# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Minimal Hyde
tagline:          'Personal Blog of Kevin Olega'
description:      'Minimal Changes is Kevin Olega's personal blog about learning, recovery and lifehacks.'
url:              http://minimalchanges.com
baseurl:          /

author:
  name:           'Kevin Olega'
  url:            https://twitter.com/kevinolega

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kevinolega
