title: minimal changes  
author: Kevin Olega
email: minimalchanges@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Minimal Changes is Kevin Olega's personal blog about learning, recovery and lifehacks.

twitter_username: kevinolega
github_username:  kevinolega
url: "http://minimalchanges.com"
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# Tracker
analytics: 'UA-18631092-1'

# Comments
disqus-shortname: minimalchanges


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html
permalink: /:title/
# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
